### ISSUE TITLE
All relevant classes that occur within 5 lines are not indexed

### ISSUE THREAD

**Issue by Shiti** [ScrapCodes/BetterDocs#10]
For example, on searching for `java.nio.mappedbytebuffer`

The file [Grep.java](https://github.com/apache/felix/blob/trunk/sigil/eclipse/core/src/org/apache/felix/sigil/eclipse/model/util/Grep.java#L65) should have listed `FileInputStream` and `FileChannel` as well

**Comment by ScrapCodes** [comment]
This is fixed in master.
