### ISSUE TITLE
A spark job to scrap GitHub project information and export that to a elastic search

### ISSUE THREAD

**Issue by sboyina** [ScrapCodes/BetterDocs#3]
Pick up some standard Java projects and write a spark job that scraps these projects to extract content (classes, filename, line number range). This extracted information has to be exported to a elastic search server.

**Comment by ScrapCodes** [comment]
In the following example json format. 

{"file":"whiteboard-master/whiteboard/networking/venus/VenusServer.java","strings":["whiteboard.core.transaction.NetworkTransactionManager","whiteboard.networking.Peer","whiteboard.networking.WhiteboardPeer"],"lineNumber":29,"score":1}

**Comment by ScrapCodes** [comment]
Pushed a change to fix this. Please take a look and report issues.
